#%RAML 1.0 DataType
displayName: 
description: Health check response
type: object
properties:
  appName: string
  appVersion: string
  mule_env: string
  mule_server: string
  status: string
  message: string
  